Updated to work with our flow.

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -1,24 +1,14 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# vim: set ft=sh
 
-set -e -u -o pipefail -o errtrace
+set -euo pipefail
 
-exec 3>&1 # make stdout available as fd 3 for the result
-exec 1>&2 # redirect all output to stderr for logging
+exec 3>&1
+exec 1>&2
 
-export root=$(dirname "${0}" | while read a; do cd "${a}" && pwd && break; done)
-# shellcheck source=./common.sh
-source "${root}/common.sh"
+cd "${1}"
 
-source="${1:-}"
-
-if [ -z "${source}" ]; then
-  echo "usage: ${0} <path/to/source>"
-  exit 1
-fi
-
-cd "${source}"
-
-payload=$(mktemp "${TMPDIR}/sonarqube-resource-out.XXXXXX")
+payload=$(mktemp /tmp/resource.XXXXXX)
 cat > "${payload}" <&0
 
 # source
@@ -28,66 +18,127 @@ username=$(jq -r '.source.username // ""' < "${payload}")
 password=$(jq -r '.source.password // ""' < "${payload}")
 project=$(jq -r '.source.project // ""' < "${payload}")
 repository=$(jq -r '.source.repository // ""' < "${payload}")
+path=$(jq -r '.params.repository // .source.dir // .source.repository // ""' < "${payload}")
+params=$(jq -rc '.params' < "${payload}")
+action=$(jq -rc '.action // ""' <<< "${params}")
+path="$(realpath "${PWD}"/"${path}")/"
 
-# params
-build=$(jq '.params' < "${payload}")
-dir=$(jq -r '.params.dir // ""' < "${payload}")
-if [ -z "${dir:-}" ] || [ ! -d "${dir}" ] ; then
-    echo "error: params.dir must be set and must point to the directory that conains the sources of the PR."
-    exit 1
-fi
-cd "${dir}"
+cd $path
 
-
-if [ -z "${base_url:-}" ]; then
-    echo "error: source.base_url can't be empty"
-    exit 1
-fi
-
-if [ ! -f "./pull-request-info" ]; then
-    echo "error: pull-request-info not found."
-    exit 1
-fi
 pr=$(cat "./pull-request-info")
 
-commit=$(echo "${pr}" | jq -r '.commit')
-build_url="${ATC_EXTERNAL_URL}/builds/${BUILD_ID}"
-if [ "${bitbucket_type}" == "server" ]; then
-    url="${base_url}/rest/build-status/1.0/commits/${commit}"
+eval_param() {
+    eval echo "$(jq -r "${1}" <<< "${params}")"
+}
 
-    json=$(echo "${build}" | jq --arg build_url "${build_url}" --arg id "${BUILD_ID}" --arg build_job_name "${BUILD_JOB_NAME}" '{
-        state: .state,
-        key: $build_job_name,
-        name: .name,
-        url: $build_url,
-        description: ("Concourse CI build, hijack as #" + $id)
-    }')
-elif [ "${bitbucket_type}" == "cloud" ]; then
-    url="${base_url}/api/2.0/repositories/${project}/${repository}/commit/${commit}/statuses/build"
+change_build_status() {
+    if [[ -z "${base_url}" ]]; then
+        echo "error: source.base_url can't be empty"
+        exit 1
+    fi
 
+    commit=$(jq -r '.commit' <<< "${pr}")
+    if [[ "${bitbucket_type}" == "server" ]]; then
+        url="${base_url}/rest/build-status/1.0/commits/${commit}"
+    elif [[ "${bitbucket_type}" == "cloud" ]]; then
+        url="${base_url}/api/2.0/repositories/${project}/${repository}/commit/${commit}/statuses/build"
+    else
+        echo "error: incorrect bitbucket server type '${bitbucket_type}'"
+        exit 1
+    fi
+    change_build_status_payload=$(jq -n \
+        --arg key "$(eval_param '.key // ""')" \
+        --arg name "$(eval_param '.name // ""')" \
+        --arg description "$(eval_param '.description // ""')" \
+        --arg state "$(eval_param '.state // ""')" \
+        --arg url "$(eval_param '.url // ""')" \
+        '{
+            state: $state,
+            key: (if $key != "" then $key else $name end),
+            name: ((if $key != "" then $key else $name end) + "-" + env.BUILD_ID),
+            url: (
+                if $url != "" then
+                    $url
+                else
+                    "\(env.ATC_EXTERNAL_URL)/builds/\(env.BUILD_ID)"
+                end
+            ),
+            description: $description|tostring
+        }'
+    )
+    curl -s --fail \
+        -u "${username}:${password}" \
+        -H "Content-Type: application/json" \
+        -XPOST "${url}" \
+        -d "${change_build_status_payload}"
 
-    # expand variables like $BUILD_ID before passing into JSON
-    name=$(echo "${build}"| jq -r '.name')
-    name=$(eval echo ${name})
-    desc=$(echo "${build}"| jq -r '.description')
-    desc=$(eval echo ${desc})
-    build_url=$(echo "${build}"| jq -r '.url')
-    build_url=$(eval echo $build_url)
-    json=$(echo "${build}" | jq --arg build_url "${build_url}" --arg id "${BUILD_ID}" --arg name "${name}" --arg desc "${desc}" '{
-        state: .state,
-        key: ($name + "-" + $id),
-        name: $name,
-        url: $build_url,
-        description: $desc
-    }')
-fi
+    jq -n --argjson pr "${pr}" --argjson payload "${change_build_status_payload}" '{
+        version: {
+            id: $pr.id|tostring,
+            title: $pr.title,
+            branch: $pr.feature_branch,
+            commit: $pr.commit,
+            updated_at: $pr.updated_at
+        },
+        metadata: [
+            {name: "state", value: $payload.state},
+            {name: "key", value: $payload.key},
+            {name: "name", value: $payload.name},
+            {name: "description", value: $payload.description}
+        ]
+    }' >&3
+}
 
-curl -s --fail -u "${username}:${password}" -H "Content-Type: application/json" -XPOST "${url}" -d "${json}"
+push() {
+    git=$(jq -r '.source.git // ""' < "${payload}")
 
-jq -n --argjson pr "${pr}" --argjson pr "${pr}" '{
-    version: {
-        id: $pr.id|tostring,
-        branch: $pr.feature_branch,
-        commit: $pr.commit
-    }
-}' >&3
+    git_payload=$(jq -nc \
+        --argjson git "${git}" \
+        --argjson pr "${pr}" \
+        --arg repository "${path}" '
+        {
+            source: (
+                $git * {
+                    branch: $pr.feature_branch
+                }
+            ),
+            params: {
+                repository: $repository
+            }
+        }
+    ')
+
+    git_payload_out=$(/opt/git-resource/out "${1}" <<< "${git_payload}")
+
+    jq -n --argjson pr "${pr}" --argjson git "${git_payload_out}" \
+        '{
+            version: {
+                id: $pr.id|tostring,
+                title: $pr.title,
+                branch: $pr.feature_branch,
+                commit: $git.version.ref
+            },
+            metadata: $git.metadata
+        }' >&3
+}
+
+case "${action}" in
+    # case for backward compatibility
+    "")
+        echo "warning: please setup the \`action\` parameter"
+        change_build_status
+    ;;
+
+    "change-build-status")
+        change_build_status
+    ;;
+
+    "push")
+        push "${@%/}"
+    ;;
+
+    *)
+        echo "error: incorrect params.action (${action})"
+        exit 1
+    ;;
+esac
